40 c4 model
hanaim-devops/devops-bp-pitstop-uitbreiding-team-monaco pull request #55
Opened 2024-10-30 10:57 UTC by GoobyTheBOI

2024-10-30 14:20 UTC, mwoaksx requested changes

2024-10-30 14:20 UTC, mwoaksx commented on docs/c4 model/c4-pitstop-C4-Container.jpg
Er missen nog wat descriptions bij sommige containers

2024-10-30 14:20 UTC, mwoaksx commented on docs/c4 model/c4-pitstop-C4-component.jpg
Zeikpuntje (😉), van `DataAcces` -> `Database` is `Reads from an writes to` (zie bijvoorbeeld bij container diagram)

2024-10-30 14:20 UTC, mwoaksx commented on docs/c4 model/c4-pitstop-C4-system_context.jpg
Dit geldt voor alle diagrammen & correct me if i am wrong, maar bij de RabbitMQ verbindingen hoef je toch geen dubbele lijnen te hebben? Kan je niet gewoon 1 lijntje maken met beide een 'pijluiteinde'?

2024-10-30 14:43 UTC, GoobyTheBOI commented on docs/c4 model/c4-pitstop-C4-component.jpg
Onze API leest alleen van de database

2024-10-31 08:44 UTC, mwoaksx approved these changes

2024-10-31 08:50 UTC, merged